import Head from 'next/head';
import { Auth, ThemeSupa } from '@supabase/auth-ui-react';
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react';
import Account from '../components/Account';
import { useEffect } from 'react';

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  useEffect(() => {
    console.log('Fired', session);
    if (session) {
      console.log('Redirect');
    }
  }, [session]);

  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-center items-center px-10">
        {!session ? (
          <>
            <h1>Welcome to Seekr</h1>
            <Auth supabaseClient={supabase} appearance={{ theme: ThemeSupa }} theme="dark" />
          </>
        ) : (
          <>
            {console.log(session)}
            <Account session={session} />
          </>
        )}
      </main>
    </>
  );
}
