import Head from 'next/head';
import Link from 'next/link';

export default function Dashboard() {
  // const { user, loading } = useAuth();
  // const router = useRouter();

  // useEffect(() => {
  //   if (!user && loading) {
  //     router.push('/');
  //   }
  //   console.log('DASHBOARD');
  // }, [user, loading]);

  // if (loading) {
  //   return <h1>Loading.........</h1>;
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-center items-center">
        <div className="text-center">
          <h1 className="text-7xl font-extrabold my-10">Dashboard</h1>
          {/* {user ? <div>Welcome, {user?.email}!</div> : <div>Loading...</div>} */}
          <Link href="/" className="text-4xl font-semibold">
            Link to home
          </Link>
        </div>
      </main>
    </>
  );
}
